const featuredbooks = [
  {
    title: "Atomic Habits",
    author: "James Clear",
    image: "https://m.media-amazon.com/images/I/81Ls+SBCLiL._AC_UF1000,1000_QL80_.jpg",
    price: "499",
    rating: 5,
  },
  {
    title: "The Power of Habit",
    author: "Charles Duhigg",
    image: "https://m.media-amazon.com/images/I/81jwnn4gHIL._AC_UF1000,1000_QL80_.jpg",
    price: "449",
    rating: 4,
  },
  {
    title: "Deep Work",
    author: "Cal Newport",
    image: "https://m.media-amazon.com/images/I/71g2ednj0JL._AC_UF1000,1000_QL80_.jpg",
    price: "599",
    rating: 5,
  },
  {
    title: "The 7 Habits of Highly Effective People",
    author: "Stephen R. Covey",
    image: "https://m.media-amazon.com/images/I/71sBtM3Yi5L._AC_UF1000,1000_QL80_.jpg",
    price: "525",
    rating: 4,
  },
  {
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    image: "https://m.media-amazon.com/images/I/71UypkUjStL._AC_UF1000,1000_QL80_.jpg",
    price: "699",
    rating: 4,
  },
  {
    title: "Start With Why",
    author: "Simon Sinek",
    image: "https://m.media-amazon.com/images/I/81l2Kj1eYLL._AC_UF1000,1000_QL80_.jpg",
    price: "499",
    rating: 4,
  },
  {
    title: "Mindset: The New Psychology of Success",
    author: "Carol S. Dweck",
    image: "https://m.media-amazon.com/images/I/81vb5hZlTPL._AC_UF1000,1000_QL80_.jpg",
    price: "459",
    rating: 5,
  },
  {
    title: "Can't Hurt Me",
    author: "David Goggins",
    image: "https://m.media-amazon.com/images/I/81o1y9pQnJL._AC_UF1000,1000_QL80_.jpg",
    price: "499",
    rating: 5,
  },
  {
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    image: "https://m.media-amazon.com/images/I/71QKQ9mwV7L._AC_UF1000,1000_QL80_.jpg",
    price: "399",
    rating: 4,
  },
  {
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    image: "https://m.media-amazon.com/images/I/81bsw6fnUiL._AC_UF1000,1000_QL80_.jpg",
    price: "379",
    rating: 4,
  },
];

const newArrivals = [
  {
    title: "Build the Life You Want",
    author: "Arthur C. Brooks & Oprah Winfrey",
    image: "https://images-na.ssl-images-amazon.com/images/I/81k6ZyJkQwL.jpg",
    price: "499",
    rating: 4,
  },
  {
    title: "The Creative Act: A Way of Being",
    author: "Rick Rubin",
    image: "https://images-na.ssl-images-amazon.com/images/I/81p+xe8cbnL.jpg",
    price: "559",
    rating: 5,
  },
  {
    title: "Hidden Potential",
    author: "Adam Grant",
    image: "https://images-na.ssl-images-amazon.com/images/I/81p7c5Vn0GL.jpg",
    price: "620",
    rating: 4,
  },
  {
    title: "Outlive: The Science and Art of Longevity",
    author: "Peter Attia MD",
    image: "https://images-na.ssl-images-amazon.com/images/I/81QFQK5QJGL.jpg",
    price: "699",
    rating: 5,
  },
  {
    title: "The Anxious Generation",
    author: "Jonathan Haidt",
    image: "https://images-na.ssl-images-amazon.com/images/I/81n5p1Qw6lL.jpg",
    price: "469",
    rating: 4,
  },
  {
    title: "Slow Productivity",
    author: "Cal Newport",
    image: "https://images-na.ssl-images-amazon.com/images/I/81v8QwQwQwL.jpg",
    price: "549",
    rating: 4,
  },
  {
    title: "The Comfort Crisis",
    author: "Michael Eastern",
    image: "https://images-na.ssl-images-amazon.com/images/I/81wFMYl4pGL.jpg",
    price: "488",
    rating: 4,
  },
  {
    title: "The Wager: A Tale of Shipwreck, Mutiny and Murder",
    author: "David Grann",
    image: "https://images-na.ssl-images-amazon.com/images/I/81y8QwQwQwL.jpg",
    price: "599",
    rating: 5,
  },
  {
    title: "The House of Flame and Shadow",
    author: "Sarah J. Maas",
    image: "https://images-na.ssl-images-amazon.com/images/I/91QFQK5QJGL.jpg",
    price: "699",
    rating: 5,
  },
  {
    title: "Fourth Wing",
    author: "Rebecca Yarros",
    image: "https://images-na.ssl-images-amazon.com/images/I/81p+xe8cbnL.jpg",
    price: "720",
    rating: 5,
  },
];
const popularBooks = [
  {
    title: "The Midnight Library",
    author: "Matt Haig",
    image: "https://images-na.ssl-images-amazon.com/images/I/81p+xe8cbnL.jpg",
    price: "720",
    rating: 5,
  },
  {
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    image: "https://images-na.ssl-images-amazon.com/images/I/81p+xe8cbnL.jpg",
    price: "720",
    rating: 5,
  },
  {
    title: "It Ends with Us",
    author: "Colleen Hoover",
    image: "https://images-na.ssl-images-amazon.com/images/I/81s6DUyQCZL.jpg",
    price: "650",
    rating: 4,
  },
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    image: "https://images-na.ssl-images-amazon.com/images/I/71aFt4+OTOL.jpg",
    price: "499",
    rating: 5,
  },
  {
    title: "The Silent Patient",
    author: "Alex Michaelides",
    image: "https://images-na.ssl-images-amazon.com/images/I/81b6U3l3p-L.jpg",
    price: "599",
    rating: 4,
  },
  {
    title: "Verity",
    author: "Colleen Hoover",
    image: "https://images-na.ssl-images-amazon.com/images/I/81z5b1gk1lL.jpg",
    price: "620",
    rating: 4,
  },
  {
    title: "The Book Thief",
    author: "Markus Zusak",
    image: "https://images-na.ssl-images-amazon.com/images/I/81eA5wT7JbL.jpg",
    price: "699",
    rating: 5,
  },
  {
    title: "The Four Winds",
    author: "Kristin Hannah",
    image: "https://images-na.ssl-images-amazon.com/images/I/81p+xe8cbnL.jpg",
    price: "730",
    rating: 4,
  },
  {
    title: "Lessons in Chemistry",
    author: "Bonnie Garmus",
    image: "https://images-na.ssl-images-amazon.com/images/I/81p+xe8cbnL.jpg",
    price: "710",
    rating: 5,
  },
  {
    title: "The Song of Achilles",
    author: "Madeline Miller",
    image: "https://images-na.ssl-images-amazon.com/images/I/81p+xe8cbnL.jpg",
    price: "680",
    rating: 5,
  },
];
export { featuredbooks, newArrivals, popularBooks };
