services:
  - type: web
    name: book-management-server
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18